name: Deploy cog-server on release

on:
  release:
    types: [published]
    
jobs:
  deploy:
    name: Connect to ovh server and deploy docker image
    runs-on: ubuntu-latest
    
    steps:      
    - name: Check out the repo
      uses: actions/checkout@v4
 
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to OVH server
      run: |
        ssh -tt -o StrictHostKeyChecking=no debian@ifremer.re << EOF
          docker container stop cog-server || true && docker image rm seatizendoi/cog-server:latest || true && \
          docker run -d --rm -v /home/debian/villien/tiles/:/app/tiles --name cog-server -p 5004:5004 seatizendoi/cog-server:latest > /dev/null 2>&1
          exit
        EOF
      